default_stages: [commit, push]
repos:
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies: ["flake8-bugbear"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
